[package]
name = "bootloader"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
debug = false
